In [1]:
## printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## imports 
import numpy as np

# 1. Vector  operations

## 1.1 Practice problem: dot product

See slide for instructions

In [2]:
# provided 
paul_wellstone = [0, 8, 2]
joe_lieberman = [4, 2, 6]
dianne_feinstein = [3, 1, 1]

In [3]:
# finding it more manually
## one example
w_l = (0*4)+(8*2) + (2*6)
print("Dot product of weinstein and lieberman is " + str(w_l))

## complete for the other two 
## your code here

Dot product of weinstein and lieberman is 28


In [4]:
# finding it using dot function in numpy
## one example
w_l_auto = np.dot(paul_wellstone, joe_lieberman)
w_l_auto

## complete for remainder
## your code here

28

## 1.2 Practice problem 2: cross product 

See slide for instructions

In [5]:
## create a 2 x 3 matrix by first creating
## a flat np array and then reshaping to those dimensions
A = np.reshape(np.array([2, 4, 1, 6, 12, 3]),
               (2, 3))
A


array([[ 2,  4,  1],
       [ 6, 12,  3]])

In [7]:
## find the cross product using the np.cross function



# 2. Matrices

## 2.1 Matrix multiplication practice

See slide for instructions

In [41]:
## we provide the matrices
Y = np.reshape(np.array([3, 1, -2, 6, 3, 4]), (2, 3))
Y

X = np.reshape(np.array([4, 2, 3, 0, 1, 2]), (3, 2))
X

array([[ 3,  1, -2],
       [ 6,  3,  4]])

array([[4, 2],
       [3, 0],
       [1, 2]])

In [42]:
## your code here


(3, 2)

(2, 3)

array([[24, 10,  0],
       [ 9,  3, -6],
       [15,  7,  6]])

## 2.2 Practice with transpose

See slide for instructions

In [48]:
## constructing matrices - content is arbitrary so 
## I generate randomly
np.random.seed(91988)
X = np.random.rand(5, 3)
X

Y = np.random.rand(5, 1)
Y

beta = np.random.rand(3, 1)
beta

array([[0.22297336, 0.88754109, 0.2065727 ],
       [0.01390197, 0.3353813 , 0.96403527],
       [0.72277712, 0.41394327, 0.87478524],
       [0.12568751, 0.25409603, 0.74629969],
       [0.83339158, 0.47150811, 0.49945983]])

array([[0.35064092],
       [0.68561768],
       [0.90472777],
       [0.77868512],
       [0.61991348]])

array([[0.6840864 ],
       [0.48380995],
       [0.69073672]])

In [8]:
## your code here

## 2.3 Practice with inverting a matrix

See slide for instructions

In [54]:
## example
X = np.reshape(np.array([1, 2, 3, 3]), (2, 2))
X


array([[1, 2],
       [3, 3]])

array([[-2, -3],
       [-4, -4]])

In [9]:
## your code here