In [8]:
## printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## imports 
import numpy as np

# 1. Vector  operations

## 1.1 Practice problem: dot product

See slide for instructions

In [2]:
# provided 
paul_wellstone = [0, 8, 2]
joe_lieberman = [4, 2, 6]
dianne_feinstein = [3, 1, 1]

In [11]:
# finding it more manually
## one example
w_l = (0*4)+(8*2) + (2*6)
print("Dot product of weinstein and lieberman is " + str(w_l))

## complete for the other two 
w_f = (0*3) + (8*1) + (2*1)
w_f
l_f = (4*3) + (2*1) + (6*1)
l_f


Dot product of weinstein and lieberman is 28


10

20

In [15]:
# finding it using dot function in numpy
## one example
w_l_auto = np.dot(paul_wellstone, joe_lieberman)
w_l_auto

## complete for remainder
w_f_auto = np.dot(paul_wellstone, dianne_feinstein)
w_f_auto
l_f_auto = np.dot(joe_lieberman, dianne_feinstein)
l_f_auto

28

10

20

## 1.2 Practice problem 2: cross product 

See slide for instructions

In [18]:
## create a 2 x 3 matrix by first creating
## a flat np array and then reshaping to those dimensions
A = np.reshape(np.array([2, 4, 1, 6, 12, 3]),
               (2, 3))
A


array([[ 2,  4,  1],
       [ 6, 12,  3]])

In [22]:
## find the cross product using the np.cross function
sen1 = A[0]
sen2 = A[1]
np.cross(sen1, sen2)

## find the cross product more manually by finding the submatrices

array([0, 0, 0])

array([2])

# 2. Matrices

## 2.1 Matrix multiplication practice

See slide for instructions

In [41]:
## we provide the matrices
Y = np.reshape(np.array([3, 1, -2, 6, 3, 4]), (2, 3))
Y

X = np.reshape(np.array([4, 2, 3, 0, 1, 2]), (3, 2))
X

array([[ 3,  1, -2],
       [ 6,  3,  4]])

array([[4, 2],
       [3, 0],
       [1, 2]])

In [42]:
## answers 
### dimensions
X.shape
Y.shape

## multiply using dot
np.dot(X, Y)

## see slides for manual answer


(3, 2)

(2, 3)

array([[24, 10,  0],
       [ 9,  3, -6],
       [15,  7,  6]])

## 2.2 Practice with transpose

See slide for instructions

In [48]:
## constructing matrices - content is arbitrary so 
## I generate randomly
np.random.seed(91988)
X = np.random.rand(5, 3)
X

Y = np.random.rand(5, 1)
Y

beta = np.random.rand(3, 1)
beta

array([[0.22297336, 0.88754109, 0.2065727 ],
       [0.01390197, 0.3353813 , 0.96403527],
       [0.72277712, 0.41394327, 0.87478524],
       [0.12568751, 0.25409603, 0.74629969],
       [0.83339158, 0.47150811, 0.49945983]])

array([[0.35064092],
       [0.68561768],
       [0.90472777],
       [0.77868512],
       [0.61991348]])

array([[0.6840864 ],
       [0.48380995],
       [0.69073672]])

In [52]:
## 1. dimensions of y-xb
result = Y-np.dot(X, beta)
result.shape

## 2. transpose to get multiplication of
## (Y-XB)*(Y-XB) to produce a 1x1 result
result2 = np.dot(np.transpose((Y-np.dot(X, beta))), (Y-np.dot(X, beta)))
result2

## 3. see slide for solution of manual distribution
## of transposes

(5, 1)

array([[0.59520073]])

## 2.3 Practice with inverting a matrix

See slide for instructions

In [54]:
## example
X = np.reshape(np.array([1, 2, 3, 3]), (2, 2))
X


array([[1, 2],
       [3, 3]])

array([[-2, -3],
       [-4, -4]])

In [60]:
## more manually
### first, find the determination of the matrix
det_X = (1*3) - (3*2)
det_X

scalar_det = 1/det_X
scalar_det
### then, flip order of matrix elements and multiple by 1/det_X
scalar_det * np.reshape(np.array([3, -2, -3, 1]), (2, 2))

## more automatically
np.linalg.inv(X)

-3

-0.3333333333333333

array([[-1.        ,  0.66666667],
       [ 1.        , -0.33333333]])

array([[-1.        ,  0.66666667],
       [ 1.        , -0.33333333]])